// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: core.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenant = `-- name: GetTenant :one
SELECT id, name, slug, status, created_at
FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, tenant_id, action, metadata, created_at
FROM audit_logs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListAuditLogs(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.TenantID,
			&i.Action,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, tenant_id, name, status, adapter_name, last_heartbeat_at, created_at
FROM nodes
ORDER BY created_at ASC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.AdapterName,
			&i.LastHeartbeatAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, status, created_at
FROM tenants
ORDER BY created_at ASC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
