// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        pgtype.UUID
	ActorID   pgtype.UUID
	TenantID  pgtype.UUID
	Action    string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
}

type BootstrapToken struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type ConfigBundle struct {
	ID            pgtype.UUID
	TenantID      pgtype.UUID
	NodeID        pgtype.UUID
	AdapterName   string
	BundleVersion int32
	Config        []byte
	Hash          string
	CreatedBy     pgtype.UUID
	CreatedAt     pgtype.Timestamptz
}

type EbpfProbeProfile struct {
	ID            pgtype.UUID
	Name          string
	MinimumKernel string
	FallbackMode  string
	Profile       []byte
	CreatedAt     pgtype.Timestamptz
}

type Membership struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	UserID    pgtype.UUID
	RoleID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type Node struct {
	ID              pgtype.UUID
	TenantID        pgtype.UUID
	Name            string
	Status          string
	AdapterName     string
	LastHeartbeatAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	AgentVersion    string
	RuntimeVersion  string
	HealthStatus    string
	HealthScore     int32
}

type NodeCapability struct {
	ID        pgtype.UUID
	NodeID    pgtype.UUID
	Name      string
	Version   string
	Manifest  []byte
	CreatedAt pgtype.Timestamptz
}

type NodeConfigApply struct {
	ID             pgtype.UUID
	NodeID         pgtype.UUID
	RolloutID      pgtype.UUID
	BundleID       pgtype.UUID
	Status         string
	Message        string
	HealthStatus   string
	HealthScore    int32
	AgentVersion   string
	RuntimeVersion string
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type NodeConfigState struct {
	NodeID                pgtype.UUID
	CurrentBundleID       pgtype.UUID
	DesiredBundleID       pgtype.UUID
	LastApplyStatus       pgtype.Text
	LastApplyMessage      pgtype.Text
	LastApplyAt           pgtype.Timestamptz
	LastKnownGoodBundleID pgtype.UUID
}

type NodeWasmPluginInstall struct {
	ID           pgtype.UUID
	NodeID       pgtype.UUID
	WasmPluginID pgtype.UUID
	DesiredState string
	CreatedAt    pgtype.Timestamptz
}

type OutboxEvent struct {
	ID            pgtype.UUID
	AggregateType string
	AggregateID   pgtype.UUID
	EventType     string
	Payload       []byte
	CreatedAt     pgtype.Timestamptz
	PublishedAt   pgtype.Timestamptz
}

type PasskeyCredential struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	CredentialID string
	PublicKey    []byte
	CreatedAt    pgtype.Timestamptz
}

type Provider struct {
	ID   pgtype.UUID
	Name string
	Slug string
}

type RefreshToken struct {
	ID            pgtype.UUID
	UserSessionID pgtype.UUID
	TokenHash     string
	RotatedAt     pgtype.Timestamptz
	ExpiresAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type Region struct {
	ID         pgtype.UUID
	ProviderID pgtype.UUID
	Name       string
	Code       string
}

type RemediationAttempt struct {
	ID                  pgtype.UUID
	RemediationPolicyID pgtype.UUID
	Status              string
	Result              []byte
	CreatedAt           pgtype.Timestamptz
}

type RemediationPolicy struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Name      string
	Mode      string
	Config    []byte
	CreatedAt pgtype.Timestamptz
}

type RiskPolicy struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Name      string
	Config    []byte
	CreatedAt pgtype.Timestamptz
}

type Role struct {
	ID          pgtype.UUID
	TenantID    pgtype.UUID
	Name        string
	Permissions []byte
	CreatedAt   pgtype.Timestamptz
}

type Rollout struct {
	ID                  pgtype.UUID
	TenantID            pgtype.UUID
	NodeID              pgtype.UUID
	BundleID            pgtype.UUID
	PreviousBundleID    pgtype.UUID
	AdapterName         string
	Status              string
	Note                string
	CreatedBy           pgtype.UUID
	RollbackOfRolloutID pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	CompletedAt         pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	Slug      string
	Status    string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type UserSession struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type WasmPlugin struct {
	ID        pgtype.UUID
	Name      string
	Version   string
	Runtime   string
	Manifest  []byte
	CreatedAt pgtype.Timestamptz
}
